language: node_js
node_js:
 - 4
 - 5
 - 6
 - 7
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn
script: npm run test:ci
